### ISSUE TITLE
Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...

### ISSUE THREAD

**Issue by dhrdzy** [uaspro/TikTokLiveDotNet#3]
Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...

**Comment by uaspro** [comment]
Hello :)
Thanks for reporting an issue. 
I haven't faced with this issue for the live streams I've tested before, can you please provide a link to a live stream on TikTok, which you are trying to connect to, so that I can try to reproduce the issue?

**Comment by dhrdzy** [comment]
string streamLinkOrStreamerNickname = ***@***.***/live";


获取房间roomId： 7193260617732606746
&gt;&gt; Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...

&gt;&gt; Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...
&gt;&gt; Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...
&gt;&gt; Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying...


不知道是不是网络的问题啊？我用的是全局代理翻墙


大乖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uaspro/TikTokLiveDotNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月27日(星期五) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uaspro/TikTokLiveDotNet] Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying... (Issue #3)





 
Hello :)
 Thanks for reporting an issue.
 I haven't faced with this issue for the live streams I've tested before, can you please provide a link to a live stream on TikTok, which you are trying to connect to, so that I can try to reproduce the issue?

**Comment by uaspro** [comment]
I will investigate and get back to you with a results :)

**Comment by dhrdzy** [comment]
好了，我换了个翻墙软件就好用了，感谢




大乖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uaspro/TikTokLiveDotNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月27日(星期五) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uaspro/TikTokLiveDotNet] Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying... (Issue #3)





 
I will investigate and get back to you with a results :)

**Comment by uaspro** [comment]
Ok, thanks for letting me know, closing this issue then. 
Feel free to reach me out in case if you face with any other issues :)

**Comment by dhrdzy** [comment]
不应该关，应该留着，写好怎么解决，这样别人遇到了就知道怎么解决了，是翻墙软件的问题




大乖
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "uaspro/TikTokLiveDotNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月27日(星期五) 晚上9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [uaspro/TikTokLiveDotNet] Websocket connection failed | Error: Missing cursor in initial fetch response.. Retrying... (Issue #3)





 
Ok, thanks for letting me know, closing this issue then.
 Feel free to reach me out in case if you face with any other issues :)

**Comment by uaspro** [comment]
I will add some note about this possible issue in the wiki (when it's ready) and also I'm planning to have some improvements implemented in the library which will include a possibility of providing custom proxy for the client.

**Comment by uaspro** [comment]
Added notes to Readme, for now - https://github.com/uaspro/TikTokLiveDotNet#notes
